### PR TITLE
Music

### PR DESCRIPTION
**Pull request by ConorMcPersonal**
Attempt to add background "music".  Not very successful yet, but the drum track is based on "Toast" as are the annoying beeps (loosely).  More a pointer to less intrusive sound.

### CODE REVIEW

**Review by mcmenaminadrian — APPROVED** [review]
Not exactly drum and bass is it? lol.

I mean it works so I see no reason not to approve it.

**Comment by ConorMcPersonal** [comment]
Need to add a sound effects 'track' with slightly different rules applied

**Comment by ConorMcPersonal** [comment]
This is now closer to where I wanted to get to - the smoke alarm now plays an absolutely crap alert sound BUT the game remains playable while it is sounding.

Sound effects get added to voice '0' in the music player and play once.  The other two voices play on a loop.  Lowest voice # wins if multiples want to play at the same time.

Sounds should be added to sound_library.c, with a TUNE_ pointer defined there.  That TUNE_ also needs to be added as extern to music.h.  game components wanting to play a sound add the relevant TUNE_ to params->effect, it gets picked up and actioned once per main loop.

**Review by mcmenaminadrian — APPROVED** [review]
This works pretty well, though the 'put put' of the single notes is bit odd, but crapness is king. Do you want to merge it? And approve my PR too maybe? Or suggest changes?

**Comment by ConorMcPersonal** [comment]
OK merged this - have not invested too much in "tuning" the output because it's a waste of time with variable timings.  Think my next PR will be about reinstating a frame count/timer as per that code snippet I sent you - we can use that to control execution rate of the main loop (hoping to run through all components once per frame, or once per 2x frames if not) and from there we can get the sound under control a bit more.  Will mean the program will reset the Spectrum when it drops back to BASIC though

**Pull request merged**
