### PR TITLE
Manic text

### LINKED ISSUE #70: Wasted screen real-estate
The former command buffer area is empty. Put something there?

Suggestions:
- Branding
- Comments from customers/the boss
- Add 1/2 new toaster slots (v easy to do)

### PR DESCRIPTION
**Pull request by ConorMcPersonal**
Using up that extra screen area with some Toast Host branding

### CODE REVIEW

**Review by mcmenaminadrian — COMMENTED** [review]
I like this!
Don't suppose it's possible to have Rick play over the main screen?
If not then no matter let's merge baby

**Comment by ConorMcPersonal** [comment]
What do you mean by main screen? The Hotel Excess in rainbow colours one?

**Comment by mcmenaminadrian** [comment]
I want the rainbow colours one

**Comment by ConorMcPersonal** [comment]
Will look into it, should be doable

**Pull request merged**
